# fly.toml app configuration file generated for doc-img-gen on 2023-06-11T09:07:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "doc-img-gen"
primary_region = "den"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
